# Copyright (c) 2015, CodiLime Inc.

FROM nginx

RUN apt-get update && apt-get install wget unzip -y
RUN mkdir -p {{frontend_dir}}

COPY config.js {{frontend_dir}}/
COPY run.sh {{frontend_dir}}/
COPY default.conf /etc/nginx/conf.d/
COPY htpasswd /etc/nginx/.htpasswd

WORKDIR {{frontend_dir}}

#omit docker build cache from this point
ENV REFRESHED_AT {{ansible_date_time.epoch}}


RUN wget {{ds_frontend_artifact_url}}
RUN unzip {{ds_frontend_package_name}}.zip

RUN cp -r build/* /usr/share/nginx/html

ENTRYPOINT ["/bin/bash", "{{frontend_dir}}/run.sh"]

CMD ["/bin/bash"]
