# Copyright (c) 2015, CodiLime Inc.

FROM ubuntu:14.04

ENV node_package_path={{node_package_path}}
ENV node_package_name={{node_package_name}}

RUN apt-get update && apt-get install wget unzip -y
RUN mkdir -p /opt/nodejs
WORKDIR /opt/nodejs
RUN wget ${node_package_path}
RUN tar -xzf ${node_package_name}.tar.gz
RUN ln -s /opt/nodejs/${node_package_name}/bin/node /usr/local/bin/node
RUN ln -s /opt/nodejs/${node_package_name}/bin/npm /usr/local/bin/npm
RUN npm install -g gulp-cli
WORKDIR /opt/nodejs/${node_package_name}/bin
