# Copyright (c) 2015, CodiLime Inc.

FROM java:jre

COPY {{wm_install_dir}} {{wm_install_dir}}
RUN mkdir -p {{wm_install_dir}}/log
WORKDIR {{wm_install_dir}}
ENTRYPOINT [ "{{wm_install_dir}}/deepsense-workflowmanager/bin/deepsense-workflowmanager" ]
CMD [ "-Dconfig.file={{wm_install_dir}}/application.conf", "-DlogFile={{wm_install_dir}}/log/deepsense-workflowmanager" ]
EXPOSE {{ds_wm_port}}
