#!/bin/bash
# Copyright (c) 2016, CodiLime Inc.
#
# Runs ./docker-compose script with latest docker images from current branch
#
# Usage: ./docker-compose-latest COMMAND [COMMAND_OPTIONS*]

if [ "$#" -lt "1" ]; then
    echo "Usage: ./docker-compose-latest COMMAND [COMMAND_OPTIONS*]"
    exit 1
fi

DOCKER_TAG="master-latest"

echo "Running docker-compose script with DOCKER_TAG=$DOCKER_TAG"
./docker-compose $DOCKER_TAG "$@"
