#!/bin/bash
# Copyright (c) 2016, CodiLime Inc.
#

rm -f docker-compose.yml

DOCKER_REPOSITORY="docker-repo.deepsense.codilime.com/deepsense_io"
DOCKER_TAG="master-latest"
sed 's|\$DOCKER_REPOSITORY|'"$DOCKER_REPOSITORY"'|g ; s|\$DOCKER_TAG|'"$DOCKER_TAG"'|g' docker-compose.tmpl.yml >> docker-compose.yml

exec docker-compose "$@"
