#!/bin/bash
# Copyright (c) 2016, CodiLime Inc.

if [ "$#" -lt "3" ]; then
    echo "Usage: ./docker-compose FRONTEND_TAG BACKEND_TAG COMMAND [COMMAND_OPTIONS*]"
    exit 1
fi

FRONTEND_TAG=$1
shift
BACKEND_TAG=$1
shift

./prepare_docker-compose docker-compose.tmpl.yml docker-compose.yml $FRONTEND_TAG $BACKEND_TAG

exec docker-compose "$@"
