INSERT INTO "users" (id,
  created,
  lastmodified,
  version,
  username,
  password,
  email,
  authorities,
  givenname,
  familyname,
  active,
  phonenumber,
  verified,
  origin,
  external_id,
  identity_zone_id,
  salt,
  passwd_lastmodified,
  legacy_verification_behavior)
VALUES ('172dce21-ea97-42cc-b2ff-30ce4ec7de9d',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  0,
  '${SEAHORSE_ADMIN_EMAIL}',
  '$2a$10$U8EnI/6IiP5gjrKXp0pqwONHg.vzwhEa3o09fu08eBtSwN4UyGVLq', -- password = 'admin'
  '${SEAHORSE_ADMIN_EMAIL}',
  'uaa.user',
  'Seahorse',
  'Admin',
  TRUE,
  null,
  TRUE,
  'uaa',
  null,
  'uaa',
  null,
  CURRENT_TIMESTAMP,
  FALSE);
