Vagrant.configure(2) do |config|
  config.vm.define "seahorse-vm" do |seahorsevm|
    seahorsevm.vm.box = "ubuntu/trusty64"
    seahorsevm.vm.hostname = "seahorse-vm"
    seahorsevm.vm.boot_timeout = 600
    seahorsevm.vm.provision "shell", path: "install_docker.sh", privileged: true
    seahorsevm.vm.provision "shell", path: "get_seahorse_images.sh", privileged: true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4295"
    vb.cpus = 4
    vb.name = "seahorse-vm"
  end
end
